#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=24:00:00
#PBS -N app-bids-hcppipeline-FS

stage=FreeSurfer
predat=`jq -r '.hcp_freesurferpre' config.json`

sub=$(jq -r "._inputs[0].meta.subject" config.json | tr -d "_")
if [[ -z $sub || $sub == null ]]; then
    sub=0
fi
bids_sub=sub-$sub

#organizing brainlife input to "bids" structure
cp -r $predat/output $bids_sub

singularity exec docker://soichih/hcppipeline \
    python ./run.py input ./ participant \
        --n_cpus 8 --stages $stage \
        --license_key "$FREESURFER_LICENSE" \
        --participant_label $sub

#move FS dirs
mv ${bids_sub}/T1w/$bids_sub output

if [[ -e output/scripts/recon-all.done ]]; then
    rm -rf ${bids_sub}
    exit 0   
else
    exit 1
fi
